apiVersion: v1
kind: Pod
metadata:
  name: redis2
  labels:
    app.kubernetes.io/name: redis2
spec:
  containers:
  - name: redis2
    image: redis:latest
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
