apiVersion: v1
kind: Service
metadata:
  name: lb-svc
spec:
  type: LoadBalancer
  selector:
    app: nginx-app  # Match this with your Deployment's pod label
  ports:
    - port: 80           # Exposed by the service
      targetPort: 80     # Exposed by the container
