apiVersion: v1
kind: Pod
metadata:
  name: memory-req3
  namespace: reqlim
spec:
  containers:
  - name: memory-req3
    image: polinux/stress
    resources:
      requests:
        memory: "9000Mi"
      limits:
        memory: "9000Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]