apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  type: NodePort
  selector:
    app: nginx-app  # Match the label from the deployment
  ports:
    - port: 80           # Service port (client accesses this)
      targetPort: 80     # Container port inside pod
      nodePort: 30080    # External port on the Node (between 30000–32767)
