apiVersion: v1
kind: Pod
metadata:
  name: memory-req2
  namespace: reqlim
spec:
  containers:
  - name: memory-req2 
    image: polinux/stress
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]